export const labelToCode: Record<string, Record<string, string>> = {
  FP: { "FP Input": "FP_Input" },
  "Requirement Dev": {
    "Software Development Planning": "SR_SDP_state",
    "Development of Concept": "SR_CD_state",
    "Development of SRS": "SR_SRS_state",
    "Traceability Analysis": "SR_TA_state",
    "Criticality Analysis": "SR_CA_state",
    "Hazard Analysis": "SR_HA_state",
    "Security Analysis": "SR_SA_state",
    "Risk Analysis": "SR_RA_state",
    "System Software Qualification": "SR_SQTPG_state",
    "System Software Acceptance": "SR_SATPG_state",
    "Configuration Management": "SR_CM_state",
    "Review and Audit": "SR_RaA_state",
  },
  "Requirement V&V": {
    "Software Planning": "SR_SVVP_state",
    "Concept Documentation Evaluation": "SR_CDE_state",
    "Software User Requirement Allocation Analysis": "SR_HRAA_state",
    "Software Requirement Evaluation": "SR_SRE_state",
    "Interface Analysis": "SR_IAVV_state",
    "Traceability Analysis": "SR_TAVV_state",
    "Criticality Analysis": "SR_CAVV_state",
    "Hazard Analysis": "SR_HAVV_state",
    "Security Analysis": "SR_SAVV_state",
    "Risk Analysis": "SR_RAVV_state",
    "System Software Qualification": "SR_VVSQTPG_state",
    "System Software Acceptance": "SR_VVSATPG_state",
    "Configuration Management": "SR_CMA_state",
    "Review and Audit": "SR_RaAVV_state",
    "Activity Summary Report": "SR_VVASRG_state",
  },
  "Design Dev": {
    "Development Software Architecture": "SD_SAD_state",
    "Development Software Design": "SD_SDD_state",
    "Traceability Analysis": "SD_TA_state",
    "Criticality Analysis": "SD_CA_state",
    "Hazard Analysis": "SD_HA_state",
    "Security Analysis": "SD_SA_state",
    "Risk Analysis": "SD_RA_state",
    "Software Component Test Plan": "SD_SCTPG_state",
    "Software Integration Test Plan": "SD_SITPG_state",
    "Software Component Test Design": "SD_SCTDG_state",
    "Software Integration Test Design": "SD_SITDG_state",
    "System Software Qualification": "SD_SQTDG_state",
    "System Software Acceptance": "SD_SATDG_state",
    "Configuration Management": "SD_CM_state",
    "Review and Audit": "SD_RaA_state",
  },
  "Design V&V": {
    "Design Evaluation": "SD_DE_state",
    "Interface Analysis": "SD_IAVV_state",
    "Traceability Analysis": "SD_TAVV_state",
    "Criticality Analysis": "SD_CAVV_state",
    "Hazard Analysis": "SD_HAVV_state",
    "Security Analysis": "SD_SAVV_state",
    "Risk Analysis": "SD_RAVV_state",
    "Software Component Test Plan": "SD_VVSCTPG_state",
    "Software Integration Test Plan": "SD_VVSITPG_state",
    "Software Component Test Design": "SD_VVSCTDG_state",
    "Software Integration Test Design": "SD_VVSITDG_state",
    "System Software Qualification": "SD_VVSQTDG_state",
    "System Software Acceptance": "SD_VVSATDG_state",
    "Configuration Management": "SD_CMVV_state",
    "Review and Audit": "SD_RaAVV_state",
    "Activity Summary Report": "SD_VVASRG_state",
  },
  "Implementation Dev": {
    "Source Code Document": "IM_SCaSCDG_state",
    "Traceability Analysis": "IM_TA_state",
    "Criticality Analysis": "IM_CA_state",
    "Hazard Analysis": "IM_HA_state",
    "Security Analysis": "IM_SA_state",
    "Risk Analysis": "IM_RA_state",
    "Software Component Test Case": "IM_CTCG_state",
    "Software Integration Test Case": "IM_SITCG_state",
    "Software Qualification Test Case": "IM_SQTCG_state",
    "Software Acceptance Test Case": "IM_SATCG_state",
    "Software Component Test Procedure": "IM_SCTPG_state",
    "Software Integration Test Procedure": "IM_SITPG_state",
    "System Software Qualification": "IM_SQTPG_state",
    "System Software Component Test Execution": "IM_SCTE_state",
    "Configuration Management": "IM_CM_state",
    "Review and Audit": "IM_RaA_state",
  },
  "Implementation V&V": {
    "Source Code Document": "IM_SCaSCDE_state",
    "Interface Analysis": "IM_IAVV_state",
    "Traceability Analysis": "IM_TAVV_state",
    "Criticality Analysis": "IM_CAVV_state",
    "Hazard Analysis": "IM_HAVV_state",
    "Security Analysis": "IM_SAVV_state",
    "Risk Analysis": "IM_RAVV_state",
    "Software Component Test Case": "IM_VVSCTCG_state",
    "Software Integration Test Case": "IM_VVSITCG_state",
    "Software Qualification Test Case": "IM_VVSQTCG_state",
    "Software Acceptance Test Case": "IM_VVSATCG_state",
    "Software Component Test Procedure": "IM_VVSCTPG_state",
    "Software Integration Test Procedure": "IM_VVSITPG_state",
    "System Software Qualification Test Procedure": "IM_VVSQTPG_state",
    "System Software Component Test Execution": "IM_VVSCTE_state",
    "Configuration Management": "IM_CMVV_state",
    "Review and Audit": "IM_RaAVV_state",
    "Activity Summary Report": "IM_VVASRG_state",
  },
  "Test Dev": {
    "Traceability Analysis": "ST_TA_state",
    "Hazard Analysis": "ST_HA_state",
    "Security Analysis": "ST_SA_state",
    "Risk Analysis": "ST_RA_state",
    "System Software Acceptance Test Execution": "ST_SATE_state",
    "System Software Acceptance Procedure Generation": "ST_SAPG_state",
    "System Software Integration Test Execution": "ST_SITE_state",
    "System Software Qualification Test Execution": "ST_SQTE_state",
    "Configuration Management": "ST_CM_state",
    "Review and Audit": "ST_RaA_state",
  },
  "Test V&V": {
    "Traceability Analysis": "ST_TAVV_state",
    "Hazard Analysis": "ST_HAVV_state",
    "Security Analysis": "ST_SAVV_state",
    "Risk Analysis": "ST_RAVV_state",
    "System Software Acceptance Test Execution": "ST_VVSATE_state",
    "System Software Acceptance Procedure Generation": "ST_VVSAPG_state",
    "System Software Integration Test Execution": "ST_VVSITE_state",
    "System Software Qualification Test Execution": "ST_VVSQTE_state",
    "Configuration Management": "ST_CMVV_state",
    "Review and Audit": "ST_RaAVV_state",
    "Activity Summary Report": "ST_VVASRG_state",
  },
  "Installation and Checkout Dev": {
    "Installation Procedure Generation": "IC_IPG_state",
    "Installation and Checkout": "IC_IaC_state",
    "Hazard Analysis": "IC_HA_state",
    "Security Analysis": "IC_SA_state",
    "Risk Analysis": "IC_RA_state",
  },
  "Installation and Checkout V&V": {
    "Installation Procedure Generation": "IC_ICAVV_state",
    "Installation and Checkout": "IC_ICVV_state",
    "Hazard Analysis": "IC_HAVV_state",
    "Security Analysis": "IC_SAVV_state",
    "Risk Analysis": "IC_RAVV_state",
    "Activity Summary Report": "IC_VVASRG_state",
    "Final Report Generation": "IC_VVFRG_state",
  },
};


